/**
 * Created by Anas on 10/2/2015.
 */
(function(){

    var myApp = angular.module("myApp", []);



    /////////////
    //Angular Controller
    ////////////
    myApp.controller('Controller1',[Controller1]);
    function Controller1(){
    }

    /////////////
    //Angular Directive
    ////////////
    myApp.directive('myCompileLinkDirective',[MyCompileLinkDirective]);

    function MyCompileLinkDirective(){
        return{
            compile:function(tempElement,tempAttribute){

                console.log("Compile Function Called");
                console.log("COMPILED : Only element and attribute are available");
                console.log(tempElement);
                console.log(tempAttribute);
                console.log("COMPILED : Scope not available");
                console.log("Changing element in compile function...");

                //Scope is not linked to the directive yet
                //You can still make changes to the HTML generated by directive

                angular
                    .element("<p>Simple Compile/Link Directive</p>")
                    .appendTo(tempElement);

                console.log("New element after change:");
                console.log(tempElement);

                return {
                    pre:function(scope,instElement,instAttribute){
                        console.log("Pre Link Function Called");
                        console.log("PRE LINK : Scope is available");
                        console.log(scope);
                    },
                    post:function(scope,instElement,instAttribute) {
                        console.log("Post Link Function Called");
                        console.log("POST LINK : Scope is available");
                        console.log(scope);
                    }
                }
            }
        }
    }


    myApp.directive('myOmgDirective1',[MyOMGDirective1]);

    function MyOMGDirective1(){
        return{
            template:'<p>Hello I am OMG#1 <div ng-transclude></div> </p>',
            transclude:true,
            compile:function(tempElement,tempAttribute){

                console.log("OMG 1 : Compile Function Called");

                return {
                    pre:function(scope,instElement,instAttribute){
                        console.log("OMG 1 : Pre Link Function Called");
                    },
                    post:function(scope,instElement,instAttribute) {
                        console.log("OMG 1 : Post Link Function Called");
                    }
                }
            }
        }
    }

    myApp.directive('myOmgDirective2',[MyOMGDirective2]);

    function MyOMGDirective2(){
        return{
            template:'<p>Hello I am OMG#2 <div ng-transclude></div> </p>',
            transclude:true,
            compile:function(tempElement,tempAttribute){

                console.log("OMG 2 : Compile Function Called");

                return {
                    pre:function(scope,instElement,instAttribute){
                        console.log("OMG 2 : Pre Link Function Called");
                    },
                    post:function(scope,instElement,instAttribute) {
                        console.log("OMG 2 : Post Link Function Called");
                    }
                }
            }
        }
    }

    myApp.directive('myOmgDirective3',[MyOMGDirective3]);

    function MyOMGDirective3(){
        return{
            template:'<p>Hello I am OMG#3</p>',
            compile:function(tempElement,tempAttribute){

                console.log("OMG 3 : Compile Function Called");

                return {
                    pre:function(scope,instElement,instAttribute){
                        console.log("OMG 3 : Pre Link Function Called");
                    },
                    post:function(scope,instElement,instAttribute) {
                        console.log("OMG 3 : Post Link Function Called");
                    }
                }
            }
        }
    }




})();